apiVersion: apps/v1
kind: Deployment
# A Deployment named nginx-deployment is created, 
# indicated by the .metadata.name field.
metadata:
  name: nginx-deployment
  labels:
    app: nginx
# The Deployment creates three replicated Pods, indicated by the .spec.replicas field.
spec:
  replicas: 3
# The .spec.selector field defines how the Deployment finds which Pods to manage.
# In this case, you select a label that is defined in the Pod template (app: nginx).
# However, more sophisticated selection rules are possible, as long as the Pod template itself
# satisfies the rule.
  selector:
    matchLabels:
      app: nginx

# The template field contains the following sub-fields:
# The Pods are labeled app: nginxusing the .metadata.labels field.
# The Pod template's specification, or .template.spec field, 
# indicates that the Pods run one container, nginx, 
# which runs the nginx Docker Hub image at version 1.14.2.
# Create one container and name it nginx using the .spec.template.spec.containers[0].name field.

  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

